brand:
  name: ATiva Assesoria e Cerimonial
menu-string: Menu

nav:
  - title: Serviços
    url: '#services'
  - title: Portfolio
    url: '#portfolio'
  - title: Sobre
    url: '#about'
  - title: Time
    url: '#team'
  - title: Contato
    url: '#contact'

copyright: Copyright &copy; ATiva Assesoria e Cerimonial

social-buttons:
  - icon: fa fa-twitter
    url: 'http://twitter.com/ativacerimonial' 
  - icon: fa fa-facebook
    url: 'https://www.facebook.com/ativacerimoniais'

quicklinks:
  - title: Privacy Policy
    url: 'https://ativacerimonial.github.io/'
  - title: Terms of Use
    url: 'https://ativacerimonial.github.io/'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
