brand:
  name: ATiva Assesoria e Cerimonial
menu-string: Menu

nav:
  - title: <b>Serviços</b>
    url: '#services'
  - title: <b>Portfolio</b>
    url: '#portfolio'
  - title: <b>Sobre</b>
    url: '#about'
  - title: <b>Time</b>
    url: '#team'
  - title: <b>Contato</b>
    url: '#contact'

copyright: Copyright &copy; ATiva Assesoria e Cerimonial

social-buttons:
  - icon: fa fa-twitter
    url: 'http://twitter.com/ativacerimonial' 
  - icon: fa fa-facebook
    url: 'https://www.facebook.com/ativacerimoniais'

quicklinks:
  - title: Privacy Policy
    url: 'https://ativacerimonial.github.io/'
  - title: Terms of Use
    url: 'https://ativacerimonial.github.io/'

modal:
  date-string: 'Data: '
  client-string: 'Cliente: '
  category-string: 'Gategoria: '
  close-icon: 'fa fa-times'
  close-string: 'Fechar'
